# Scaffolding generated by Casein v5.1.1.5

module Casein
  class OthersController < Casein::CaseinController
  
    ## optional filters for defining usage according to Casein::AdminUser access_levels
    # before_filter :needs_admin, :except => [:action1, :action2]
    # before_filter :needs_admin_or_current_user, :only => [:action1, :action2]
  
    def index
      @casein_page_title = 'Others'
  		@others = Other.order(sort_order(:title)).paginate :page => params[:page]
    end
  
    def show
      @casein_page_title = 'View other'
      @other = Other.find params[:id]
    end
  
    def new
      @casein_page_title = 'Add a new other'
    	@other = Other.new
    end

    def create
      @other = Other.new other_params
    
      if @other.save
        flash[:notice] = 'Other created'
        redirect_to casein_others_path
      else
        flash.now[:warning] = 'There were problems when trying to create a new other'
        render :action => :new
      end
    end
  
    def update
      @casein_page_title = 'Update other'
      
      @other = Other.find params[:id]
    
      if @other.update_attributes other_params
        flash[:notice] = 'Other has been updated'
        redirect_to casein_others_path
      else
        flash.now[:warning] = 'There were problems when trying to update this other'
        render :action => :show
      end
    end
 
    def destroy
      @other = Other.find params[:id]

      @other.destroy
      flash[:notice] = 'Other has been deleted'
      redirect_to casein_others_path
    end
  
    private
      
      def other_params
        params.require(:other).permit(:title, :author, :date, :body, :image)
      end

  end
end